---

# common roles for all nodes
- hosts: all
  become: yes
  roles:
    - role: common

# individual roles per hostgroup
- hosts: db
  roles:
    - role: mongodb
      become: yes

- hosts: jupyterhub
  roles:
    - role: jupyterhub
      become: yes
    - role: user
      become: yes
