# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define :vagrant
  config.vm.hostname = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.groups = {
      "db" => [:vagrant],
      "jupyterhub" => [:vagrant]
    }
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 9001, host: 9001
end
