---

- name: install latest version of useful packages
  apt: name={{item}} state=latest update_cache=yes cache_valid_time={{apt_cache_valid_time}}
  with_items:
    - python-setuptools
    - python-pip
    - language-pack-en
